# Generated by Django 4.2.5 on 2023-10-09 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_post_published_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LastWeeklyNotification',
        ),
    ]
